# Site
name: "CountrysideLife"
title: "CountrysideLife"
description: "在泰国暖武里府的陪读生活"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /GardenCondo
google_analytics: 'UA-46278016-1'
# disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  kevin:
    name: Zheng, Yang
    display_name: Kevin
    avatar: 'assets/images/coder.png'
    # gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: kevin.cn.zhengyang@gmail.com
    web: 
    twitter: 
    description: "Kevin is an old coder."
  john:
    name: Li, Li
    display_name: Shell
    avatar: 'assets/images/shell.jpg'
    # gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: shellily77@gmail.com
    web: 
    twitter: 
    description: "Shell is a beautiful designer."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
